/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as DeskIndexImport } from './routes/desk/index'
import { Route as AgentIndexImport } from './routes/agent/index'
import { Route as PublicIndexImport } from './routes/_public/index'

// Create/Update Routes

const DeskIndexRoute = DeskIndexImport.update({
  path: '/desk/',
  getParentRoute: () => rootRoute,
} as any)

const AgentIndexRoute = AgentIndexImport.update({
  path: '/agent/',
  getParentRoute: () => rootRoute,
} as any)

const PublicIndexRoute = PublicIndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public/': {
      preLoaderRoute: typeof PublicIndexImport
      parentRoute: typeof rootRoute
    }
    '/agent/': {
      preLoaderRoute: typeof AgentIndexImport
      parentRoute: typeof rootRoute
    }
    '/desk/': {
      preLoaderRoute: typeof DeskIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  PublicIndexRoute,
  AgentIndexRoute,
  DeskIndexRoute,
])

/* prettier-ignore-end */
